# Generated by Django 3.2.13 on 2023-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crowdinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoot_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('total_count', models.IntegerField()),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
                ('vis_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='crowdinfo_concordance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='null', max_length=50)),
                ('avg_count', models.IntegerField()),
                ('max_count', models.IntegerField()),
                ('min_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warn_time', models.DateTimeField(auto_now=True)),
                ('warn_type', models.CharField(max_length=50, null=True)),
                ('warn_area', models.CharField(max_length=50, null=True)),
                ('warn_description', models.CharField(max_length=50, null=True)),
                ('camera_id', models.IntegerField(default=0, null=True)),
                ('info', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
