# Generated by Django 3.2.13 on 2023-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='soft_delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoot_time', models.CharField(default='1970-01-01 00:00:00', max_length=50)),
                ('total_count', models.IntegerField()),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
                ('vis_count', models.IntegerField()),
                ('label', models.CharField(default='is deleted', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tracking_object_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('inshoot_time', models.DateTimeField(db_index=True, null=True)),
                ('outshoot_time', models.DateTimeField(null=True)),
                ('person_info', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='crowdinfo_concordance',
        ),
    ]
