# Generated by Django 3.2.13 on 2023-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0002_auto_20230314_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistic_crowdinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.DateTimeField(null=True)),
                ('delta_count', models.IntegerField()),
                ('avg_vis', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='soft_delete',
            name='label',
        ),
        migrations.AlterField(
            model_name='crowdinfo',
            name='vis_count',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='soft_delete',
            name='shoot_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
